# Updated GitHub Actions workflow to use the Gradle Setup Action with JDK 21 and Gradle 8.4

name: Spring Boot Showcase CI/CD

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.4

      - name: Build with Gradle
        run: ./gradlew build

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST 
          -H "Accept: application/json" 
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" 
          -H "Content-Type: application/json" 
          -d '{
            "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",
            "branch": "main",
            "commit": "${{ github.sha }}",
            "version": "${{ github.ref_name }}"
          }' 
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
